<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>08742f4b-fb10-44f7-a43e-c7dadf00b3b4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Ardalis.Result.AspNetCore" Version="10.1.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App\Features\AppointmentChangeRequests\Commands\CreateAppointmentChangeRequestCommand\" />
    <Folder Include="App\Features\AppointmentChangeRequests\Commands\ApplyAppointmentChangeRequestCommand\" />
    <Folder Include="App\Features\AppointmentChangeRequests\Queries\GetMyAppointmentChangeRequests\" />
    <Folder Include="App\Features\Instructors\Commands\UpdateMyInstructorDetailCommand\" />
    <Folder Include="App\Features\Instructors\Queries\GetMyInstructorDetailQuery\" />
    <Folder Include="App\Features\Instructors\Queries\SearchInstructorQuery\" />
    <Folder Include="App\Features\Users\Queries\GetMyUserQuery\" />
    <Folder Include="App\Features\Users\Queries\GetUserQuery\" />
    <Folder Include="App\Features\Users\Queries\GetUsersQuery\" />
    <Folder Include="App\Features\Users\Queries\SearchUserQuery\" />
    <Folder Include="Infrastructure\Data\Configuration\" />
  </ItemGroup>

</Project>
